src/lists/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('lists/new', views.new_list, name='new_list'),
    path('lists/<int:id>/', views.view_list, name='view_list'),  # Definição do ID da lista
    path('lists/<int:id>/add_item', views.view_list, name='view_list_add_item'),  # Pode ser necessário adicionar essa rota para POST
]

src/superlists/urls.py
from django.urls import include, path
from lists import views as list_views  

urlpatterns = [
    path("", list_views.home_page, name="home"),
    path("lists/", include("lists.urls")),  
]

src/lists/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE
    )

    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])
    
    @property
    def name(self):
        return self.item_set.first().text



class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('id',)
        unique_together = ("list", "text")

src/lists/forms.py
from django import forms
from lists.models import Item
from django.core.exceptions import ValidationError

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.widgets.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control form-control-lg",
                }
            ),
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()
    
class ExistingListItemForm(forms.models.ModelForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

src/lists/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ValidationError
from lists.models import List, Item
from lists.forms import ExistingListItemForm, ItemForm

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    else:
        form = ItemForm()
    return render(request, "list.html", {"list": list_, "form": form})


# View para a página inicial
def home_page(request):
    form = ItemForm()  # Cria uma instância do ItemForm
    return render(request, 'home.html', {'form': form})  # Passa o form para o contexto

# View para criar uma nova lista
def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        nulist = List.objects.create()
        if request.user.is_authenticated:
            nulist.owner = request.user
            nulist.save()
        form.save(for_list=nulist)
        return redirect(nulist)
    else:
        return render(request, "home.html", {"form": form})
    
def my_lists(request, email):
    return render(request, "my_lists.html")

src/lists/templates/base.html
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>To-Do lists</title>
  <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/base.css" rel="stylesheet">
</head>

<body>
  <div class="container">

    <nav class="navbar">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Superlists</a>
        {% if user.email %}
        <a href="{% url 'my_lists' user.email %}">My lists</a>
          <span class="navbar-text">Logged in as {{ user.email }}</span>
          <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button id="id_logout" class="btn btn-outline-secondary" type="submit">Log out</button>
          </form>
        {% else %}
          <form method="POST" action="{% url 'send_login_email' %}">
            <div class="input-group">
              <label class="navbar-text me-2" for="id_email_input">
                Enter your email to log in
              </label>
              <input
                id="id_email_input"
                name="email"
                class="form-control"
                placeholder="your@email.com"
              />
              {% csrf_token %}
            </div>
          </form>
        {% endif %}
      </div>
    </nav>

    {% if messages %}
      <div class="row">
        <div class="col-md-8">
          {% for message in messages %}
            {% if message.level_tag == 'success' %}
              <div class="alert alert-success">{{ message }}</div>
            {% else %}
              <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    {% endif %}


    <div class="row justify-content-center p-5 bg-body-tertiary rounded-3">
      <div class="col-lg-6 text-center">
        <h1 class="display-1 mb-4">{% block header_text %}{% endblock %}</h1>
        {% block list_form %}
        <form method="POST" action="{% block form_action %}{% endblock %}" >
          {% csrf_token %}
        </div>
        {% endif %}
      </form>
        {% block table %}
        {% endblock %}
      </div>
    </div>

    </div>

    <script src="/static/lists.js"></script>
    <script>
      initialize("#id_text", ".invalid-feedback");
    </script>

  </body>
</html>

src/lists/templates/home.html
{% extends "base.html" %}

{% block header_text %}
Start a new To-Do list
{% endblock %}

{% block form_action %}
{% url 'new_list' %}
{% endblock %}

src/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}
    {% url 'view_list' list.id %}
{% endblock %}

{% block content %}
    <!-- Exibe erro se houver -->
    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}

    <!-- Tabela de Itens -->
    <table class="table" id="id_list_table">
        {% for item in list.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
        {% endfor %}
    </table>

    <!-- Formulário de Novo Item -->
    <form method="POST" action="{% block form_action %}{% endblock %}">
        {% csrf_token %}
        <input type="text" name="item_text" id="id_item_text" placeholder="Enter a new item" required>
        <button type="submit">Add Item</button>
    </form>
{% endblock %}